import {randomBytes} from 'node:crypto';
import {db} from './db';
import {encrypt,decrypt,signed,verified} from './auth';
export const SOURCES=[{id:'1DZ_H3vIVseQ3LKC8FgrhfezM-4JHznZUFiKvLWhqap0',sheets:['ЗАГРУЗ','Нормы','Лист14','БД. СОТ']},{id:'1W3VK9Fw71lYdw1Klcsn_za5-2EhvLoXIAKZVYOCnKcs',sheets:['БД.ОП'],operationSheetId:895010191}];
export interface SheetSnapshot {spreadsheet:string;sheet:string;values:string[][];at:string}
type Tokens={access_token:string;refresh_token?:string;expires_at:number};
const callback=()=>`${process.env.APP_URL}/api/v1/google/callback`;
export function authorization(){if(!process.env.GOOGLE_CLIENT_ID||!process.env.GOOGLE_CLIENT_SECRET)throw new Error('Укажите GOOGLE_CLIENT_ID и GOOGLE_CLIENT_SECRET на сервере');const state=signed({kind:'google',nonce:randomBytes(24).toString('hex'),exp:Date.now()+10*60000});const url=new URL('https://accounts.google.com/o/oauth2/v2/auth');url.search=new URLSearchParams({client_id:process.env.GOOGLE_CLIENT_ID,redirect_uri:callback(),response_type:'code',scope:'https://www.googleapis.com/auth/spreadsheets.readonly',access_type:'offline',prompt:'consent',state}).toString();return {url:url.toString(),state};}
async function tokenRequest(params:Record<string,string>){const r=await fetch('https://oauth2.googleapis.com/token',{method:'POST',headers:{'Content-Type':'application/x-www-form-urlencoded'},body:new URLSearchParams({...params,client_id:process.env.GOOGLE_CLIENT_ID!,client_secret:process.env.GOOGLE_CLIENT_SECRET!}),signal:AbortSignal.timeout(20000)});if(!r.ok)throw new Error('Google не подтвердил доступ. Подключите аккаунт заново.');return await r.json() as {access_token:string;refresh_token?:string;expires_in:number};}
export async function exchange(code:string,state:string){if(verified(state)?.kind!=='google')throw new Error('Срок подключения Google истёк');const t=await tokenRequest({code,redirect_uri:callback(),grant_type:'authorization_code'});const previous=await db.credential.findUnique({where:{id:'google'}});const refresh=t.refresh_token||(previous?decrypt<Tokens>(previous.encrypted).refresh_token:undefined);await db.credential.upsert({where:{id:'google'},create:{id:'google',encrypted:encrypt({...t,refresh_token:refresh,expires_at:Date.now()+t.expires_in*1000})},update:{encrypted:encrypt({...t,refresh_token:refresh,expires_at:Date.now()+t.expires_in*1000})}});}
async function accessToken(){const c=await db.credential.findUnique({where:{id:'google'}});if(!c)throw new Error('Сначала подключите Google');let t=decrypt<Tokens>(c.encrypted);if(t.expires_at<Date.now()+60000){if(!t.refresh_token)throw new Error('Подключите Google заново');const refreshed=await tokenRequest({refresh_token:t.refresh_token,grant_type:'refresh_token'});t={...t,...refreshed,expires_at:Date.now()+refreshed.expires_in*1000};await db.credential.update({where:{id:'google'},data:{encrypted:encrypt(t)}});}return t.access_token;}
export async function fetchSnapshots():Promise<SheetSnapshot[]>{const token=await accessToken();const result:SheetSnapshot[]=[];
  const source=SOURCES[1],metadataUrl=new URL(`https://sheets.googleapis.com/v4/spreadsheets/${source.id}`);
  metadataUrl.searchParams.set('ranges',"'БД.ОП'!A1");metadataUrl.searchParams.set('fields','sheets(properties(sheetId,title))');
  const metadataResponse=await fetch(metadataUrl,{headers:{Authorization:`Bearer ${token}`},signal:AbortSignal.timeout(30000)});
  if(!metadataResponse.ok)throw new Error('Не удалось проверить идентификатор БД.ОП');
  const metadata=await metadataResponse.json();
  if(!metadata.sheets?.some((sheet:{properties:{sheetId:number;title:string}})=>sheet.properties.sheetId===source.operationSheetId&&sheet.properties.title==='БД.ОП'))throw new Error('БД.ОП не соответствует разрешённому листу 895010191');
  for(const source of SOURCES){const url=new URL(`https://sheets.googleapis.com/v4/spreadsheets/${source.id}/values:batchGet`);for(const sheet of source.sheets)url.searchParams.append('ranges',`'${sheet}'!A1:ZZ5000`);url.searchParams.set('valueRenderOption','FORMATTED_VALUE');const r=await fetch(url,{headers:{Authorization:`Bearer ${token}`},signal:AbortSignal.timeout(30000)});if(!r.ok)throw new Error(`Google Sheets: ${r.status}. Проверьте доступ к источнику.`);const data=await r.json();for(let i=0;i<source.sheets.length;i++)result.push({spreadsheet:source.id,sheet:source.sheets[i],values:data.valueRanges[i]?.values||[],at:new Date().toISOString()});}
  return result;
}
