import {defaultCalendar, type Workspace,type Project,type Norm,type Operation} from './types';
const norm=(work:number,machineId?:string):Norm=>({type:'static',length:1,secondsPerMeter:0,toolSeconds:machineId?work:0,toolCount:machineId?1:0,take:0,work,put:0,extra:0,repeats:1,setup:0,machineId});
export function emptyProject(id:string,name='Новый проект'):Project{return {id,revision:1,normVersion:1,code:'ПР-001',name,quantity:100,startDate:new Date().toISOString().slice(0,10),deadline:new Date(Date.now()+30*86400000).toISOString().slice(0,10),zone:'Asia/Shanghai',status:'open',template:false,comment:'',readiness:{'Материалы':false,'Техкарта':false,'Комплектация':false},employeeIds:[],stages:[],edges:[],bufferHours:1,opening:{},supplies:[],assignments:[],baseline:[],actuals:[],movements:[],demo:false};}
export function seedWorkspace():Workspace{
  const operations:Operation[]=[{id:'op-cut',code:'PCB_CUT',name:'Разделение плат',norm:norm(28.8,'machine-cut')},{id:'op-solder',code:'PCB_SOLDER',name:'Пайка плат',norm:norm(72)},{id:'op-wash',code:'PCB_QC',name:'Отмывка и ОТК плат',norm:norm(3600/545,'machine-wash')},{id:'op-pack',code:'PCB_PACK',name:'Упаковка',norm:norm(18)}];
  const names=['Оператор 01','Оператор 02','Оператор 03','Оператор 04'];
  const employees=names.map((name,i)=>({id:`person-${i+1}`,name,calendar:defaultCalendar(),skills:Object.fromEntries(operations.map(o=>[o.id,{allowed:true,stars:i===0?4:3,coefficient:1}]))}));
  const project=emptyProject('project-demo','Сборка контроллеров');
  Object.assign(project,{code:'ПР-2026 / 014',quantity:7000,startDate:'2026-09-23',deadline:'2026-10-16',demo:true,employeeIds:employees.map(e=>e.id),comment:'Демонстрационный маршрут по примеру Лист14. Нормы: 125, 50 и 545 шт./ч из Нормы; упаковка и оборудование — демонстрационные допущения.',readiness:{'Материалы':true,'Техкарта':true,'Комплектация':true}});
  project.stages=operations.map((o,i)=>({id:`stage-${i+1}`,name:['Заготовка платы','Паяная плата','Плата после ОТК','Готовый контроллер'][i],index:`ПФ-${String(i+1).padStart(3,'0')}`,final:i===3,x:[30,340,340,30][i],y:[30,30,240,240][i],operations:[{id:`route-op-${i+1}`,operationId:o.id,code:o.code,name:o.name,norm:structuredClone(o.norm),workers:4,mode:'independent'}]}));
  project.edges=project.stages.slice(0,-1).map((s,i)=>({id:`edge-${i}`,source:s.id,target:project.stages[i+1].id,quantity:1,transferBatch:50}));
  return {schemaVersion:1,projects:[project],employees,machines:[{id:'machine-cut',name:'Участок разделения',count:2,calendar:defaultCalendar()},{id:'machine-wash',name:'Установка отмывки',count:1,calendar:defaultCalendar()}],operations};
}
