'use client';
import {useState,useEffect,useRef} from 'react';
import {LayoutGrid,Layers3,UsersRound,Settings2,Database,ArrowUpRight,Plus,ChevronDown,ChevronRight,GitBranch,Table2,CalendarDays,Package,SlidersHorizontal,MoreHorizontal,Download,Upload,Copy,Archive,Trash2,RotateCcw,Check,LogOut,Search,PanelLeftClose,ArrowRight,Clock3,Zap,Truck,FileInput,X,LockKeyhole} from 'lucide-react';
import {Client,download} from './client';
import {uid,type Workspace,type Project,type Scenario,type Assignment,type Job} from '../domain/types';
import {emptyProject} from '../domain/seed';
import {calculateNorm} from '../domain/norms';
import {FormErrorContext,Modal,Field,Badge,num,dateLabel,timeLabel} from './components';
import RouteEditor from './RouteEditor';
import {Timeline} from './Timeline';
import {Norms,Materials,ActualReport} from './Reports';
import {ProjectForm,ActualForm,MovementForm,AssignmentForm} from './ProjectForms';
import Catalog from './Catalog';
import type {ImportPreview} from '../domain/importer';
type Screen='project'|'overview'|'employees'|'machines'|'operations'|'imports'|'templates'|'archive';
export default function Planner({demo=false}:{demo?:boolean}){
  const client=useRef<Client|null>(null);const [w,setW]=useState<Workspace>(),[loggedOut,setLoggedOut]=useState(false),[error,setError]=useState(''),[notice,setNotice]=useState(''),[selected,setSelected]=useState('project-demo'),[screen,setScreen]=useState<Screen>('project'),[tab,setTab]=useState('route'),[query,setQuery]=useState(''),[busy,setBusy]=useState('');
  const [edit,setEdit]=useState<Project>(),[deleteProject,setDelete]=useState<Project>(),[confirmCode,setConfirmCode]=useState(''),[planning,setPlanning]=useState(false),[mode,setMode]=useState<'first'|'throughput'>('first'),[job,setJob]=useState<Job>(),[detail,setDetail]=useState<Assignment>(),[actual,setActual]=useState<Assignment>(),[assignment,setAssignment]=useState<Assignment|null|undefined>(),[movement,setMovement]=useState(false),[preview,setPreview]=useState<(ImportPreview&{id:string})>(),[connected,setConnected]=useState(false),[secondsConfirmed,setSecondsConfirmed]=useState(false),[employeesRow,setEmployeesRow]=useState(55),[menu,setMenu]=useState(false),[sideOpen,setSideOpen]=useState(false);
  const inputFile=useRef<HTMLInputElement>(null);
  useEffect(()=>{client.current=new Client(demo);client.current.load().then(data=>{setW(data);if(!data.projects.some(p=>p.id===selected))setSelected(data.projects[0]?.id||'');}).catch(e=>{if(e.message.includes('Войдите'))setLoggedOut(true);else setError(e.message);});},[demo]);
  useEffect(()=>{if(!demo&&w)client.current?.request('google/status').then(s=>setConnected(s.connected)).catch(()=>{});},[demo,!!w]);
  const run=async(fn:()=>Promise<void>)=>{setError('');try{await fn();}catch(e){setError((e as Error).message);notify((e as Error).message);}};
  const notify=(s:string)=>{setNotice(s);setTimeout(()=>setNotice(''),5000);};
  const save=async(p:Project)=>{const next=await client.current!.save(p);setW(next);setEdit(undefined);setSelected(p.id);notify('Изменения сохранены');};
  const action=async(id:string,name:string,body:unknown={})=>{setW(await client.current!.action(id,name,body));setMenu(false);notify('Изменения сохранены');};
  const open=(id:string)=>{setSelected(id);setScreen('project');setTab('route');setSideOpen(false);};
  const project=w?.projects.find(p=>p.id===selected),active=w?.projects.filter(p=>p.status==='open'&&!p.template)||[];
  const current=detail?w?.projects.find(p=>p.id===detail.projectId):project;
  const calc=()=>run(async()=>{setJob(undefined);setBusy('Подготовка расчёта…');try{setJob(await client.current!.calculate(selected,mode,setBusy));}finally{setBusy('');}});
  if(loggedOut)return <div className="login-page"><div className="login-card"><div className="brand"><div className="brand-mark"><Layers3 size={24}/></div><strong>поток<span>производство</span></strong></div><h1>Рабочее место планировщика</h1><p>Войдите, чтобы открыть проекты и ресурсный план.</p><form onSubmit={e=>{e.preventDefault();const formData=new FormData(e.currentTarget);run(async()=>{await client.current!.request('auth/login',{login:formData.get('login'),password:formData.get('password')});setLoggedOut(false);const data=await client.current!.load();setW(data);setSelected(data.projects[0]?.id||'');});}}><Field label="Логин"><input name="login" defaultValue="planner" required autoComplete="username"/></Field><Field label="Пароль"><input name="password" type="password" required autoComplete="current-password"/></Field>{error&&<p role="alert" className="negative">{error}</p>}<button className="primary full-width">Войти <ArrowRight size={16}/></button></form></div></div>;
  if(!w)return <div className="loading-page"><div className="brand-mark"><Layers3 size={28}/></div><h2>{error?'Не удалось открыть платформу':'Загружаем рабочее пространство…'}</h2>{error&&<p role="alert">{error}</p>}</div>;
  const completed=project?.movements.filter(m=>m.kind==='output'&&project.stages.find(s=>s.id===m.stageId)?.final).reduce((s,m)=>s+m.quantity,0)||0;
  const finalDate=project?.assignments.reduce((last,a)=>last>a.end?last:a.end,'');
  return <FormErrorContext.Provider value={error}><div className="app-shell"><aside className={'sidebar '+(sideOpen?'show':'')}><div className="brand"><div className="brand-mark"><Layers3 size={22}/></div><strong>поток<span>производство</span></strong><button className="icon-button sidebar-toggle" onClick={()=>setSideOpen(false)} aria-label="Скрыть меню"><PanelLeftClose size={16}/></button></div><div className="workspace-label"><div className="workspace-icon">П</div><span>Производственная площадка<small>Рабочее пространство</small></span></div><nav className="main-nav"><button className={screen==='overview'?'active':''} onClick={()=>{setScreen('overview');setSideOpen(false);}}><LayoutGrid size={18}/>Ресурсный план</button><button className={screen==='project'?'active':''} onClick={()=>{setScreen('project');setSideOpen(false);}}><Layers3 size={18}/>Проекты <span className="count">{active.length}</span></button><button className={screen==='employees'?'active':''} onClick={()=>setScreen('employees')}><UsersRound size={18}/>Сотрудники</button><button className={screen==='machines'?'active':''} onClick={()=>setScreen('machines')}><Settings2 size={18}/>Оборудование</button><button className={screen==='operations'?'active':''} onClick={()=>setScreen('operations')}><Database size={18}/>БД.ОП</button></nav><div className="sidebar-section"><span>ПРОЕКТЫ В РАБОТЕ</span><button className="icon-button" aria-label="Новый проект" onClick={()=>setEdit(emptyProject(uid()))}><Plus size={15}/></button></div><div className="project-list">{active.map(p=><button className={p.id===selected&&screen==='project'?'selected':''} key={p.id} onClick={()=>open(p.id)}><i/><span>{p.name}<small>{p.code}</small></span>{p.id===selected&&screen==='project'&&<ChevronRight size={14}/>}</button>)}<button className="new-project" onClick={()=>setEdit(emptyProject(uid()))}><Plus size={15}/>Новый проект</button></div><div className="sidebar-bottom"><button onClick={()=>setScreen('templates')}><Copy size={16}/>Шаблоны проектов</button><button onClick={()=>setScreen('archive')}><Archive size={16}/>Архив и корзина</button><button className={screen==='imports'?'active':''} onClick={()=>setScreen('imports')}><FileInput size={16}/>Источники данных</button><div className="user-info"><div className="avatar">ПЛ</div><span>Планировщик<small>{demo?'Демонстрационный режим':'Рабочая версия'}</small></span>{!demo&&<button className="icon-button" aria-label="Выйти" onClick={()=>run(async()=>{await client.current!.request('auth/logout',{});setLoggedOut(true);})}><LogOut size={16}/></button>}</div></div></aside>
  <main><header className="topbar"><button className="icon-button mobile-menu" onClick={()=>setSideOpen(!sideOpen)} aria-label="Открыть меню"><LayoutGrid size={20}/></button><div className="breadcrumbs"><span>Рабочее пространство</span><ChevronRight size={13}/><strong>{({project:'Проекты',overview:'Ресурсный план',employees:'Сотрудники',machines:'Оборудование',operations:'БД.ОП',imports:'Источники данных',templates:'Шаблоны',archive:'Архив'})[screen]}</strong></div><div className="topbar-right">{demo&&<Badge tone="amber">Демо · данные этого браузера</Badge>}<span className="saved-status"><i/>Сохранено</span><div className="avatar small">ПЛ</div></div></header>
  {error&&<div className="alert error" role="alert"><span>{error}</span><button className="icon-button" aria-label="Закрыть ошибку" onClick={()=>setError('')}><X size={16}/></button></div>}{notice&&<div className="toast" role="status"><Check size={16}/>{notice}</div>}
  {screen==='project'&&project?<><div className="project-header"><div className="project-heading"><div><div className="eyebrow">{project.code} <span>/</span> СБОРОЧНОЕ ПРОИЗВОДСТВО</div><div className="title-row"><h1>{project.name}</h1><Badge tone={project.status==='open'?'green':'neutral'}>{project.template?'Шаблон':project.status==='open'?'В работе':project.status==='closed'?'Закрыт':'В корзине'}</Badge></div><p>{project.demo?'Демонстрационный проект по структуре Лист14':'Планирование, исполнение и движение полуфабрикатов'}</p></div><div className="actions project-actions"><button onClick={()=>setEdit(structuredClone(project))}><SlidersHorizontal size={16}/>Параметры</button><button className="primary" disabled={project.status!=='open'||project.template} onClick={()=>{setPlanning(true);setJob(undefined);}}><Zap size={16}/>Автопланирование</button><div className="menu-anchor"><button className="icon-button bordered" aria-label="Действия проекта" onClick={()=>setMenu(!menu)}><MoreHorizontal size={20}/></button>{menu&&<div className="dropdown"><button onClick={()=>run(async()=>download(project.code+'.json',await client.current!.exportProject(project.id)))}><Download size={15}/>Экспорт JSON</button><button onClick={()=>run(()=>action(project.id,'clone',{template:true}))}><Copy size={15}/>Сохранить как шаблон</button><button onClick={()=>run(()=>action(project.id,'clone'))}><Copy size={15}/>Создать копию</button><button onClick={()=>run(()=>action(project.id,project.status==='closed'?'reopen':'close'))}><Archive size={15}/>{project.status==='closed'?'Открыть снова':'Закрыть проект'}</button><button className="danger" onClick={()=>{setDelete(project);setConfirmCode('');setMenu(false);}}><Trash2 size={15}/>Удалить проект</button></div>}</div></div></div>
  <div className="project-metrics"><div><span>Объём заказа</span><strong>{num(project.quantity)} <small>шт.</small></strong></div><div><span>Срок готовности</span><strong>{dateLabel(project.deadline)} <Badge tone={finalDate&&finalDate.slice(0,10)>project.deadline?'red':'neutral'}>{finalDate?'План: '+dateLabel(finalDate):'Нет плана'}</Badge></strong></div><div><span>Команда проекта</span><strong>{project.employeeIds.length} <small>сотрудника</small><span className="mini-avatars">{project.employeeIds.slice(0,3).map((id,i)=><i className={'avatar-'+i} key={id}>{i+1}</i>)}</span></strong></div><div><span>Готовая продукция</span><strong>{num(completed)} <small>/ {num(project.quantity)} шт.</small></strong><div className="progress-line"><i style={{width:Math.min(100,completed/project.quantity*100)+'%'}}/></div></div></div>
  <div className="project-tabs">{[['route','Схема',GitBranch],['norms','Нормативы',Table2],['plan','План / факт',CalendarDays],['materials','Движение материалов',Package]].map(([id,label,Icon])=>{const I=Icon as typeof GitBranch;return <button className={tab===id?'active':''} key={id as string} onClick={()=>setTab(id as string)}><I size={17}/>{label as string}</button>;})}<span className="tabs-right">{Object.values(project.readiness).every(Boolean)?<><Check size={13}/>Материалы готовы</>:<><Clock3 size={13}/>Проверить готовность</>}</span></div></div>
  <div className={'project-content '+(tab==='route'?'route-content':'')}>
    {tab==='route'&&<RouteEditor key={project.id} project={project} workspace={w} onSave={p=>run(()=>save(p))} onError={setError}/>}
    {tab==='norms'&&<Norms project={project}/>}
    {tab==='plan'&&<><Timeline key={project.id} workspace={w} project={project} onAssignment={setDetail} onNew={()=>setAssignment(null)}/><details className="fact-summary"><summary>Сводка факта по операциям</summary><ActualReport project={project}/></details></>}
    {tab==='materials'&&<Materials key={project.id} project={project} onNew={()=>setMovement(true)}/>}
  </div></>:<div className="page-content">
    {screen==='overview'&&<Timeline workspace={w} onAssignment={setDetail} onProject={open}/>}
    {['employees','machines','operations'].includes(screen)&&<Catalog key={screen} workspace={w} view={screen as 'employees'|'machines'|'operations'} onSave={(kind,item)=>run(async()=>{setW(await client.current!.catalog(kind,item));notify('Справочник сохранён');})}/>}
    {(screen==='templates'||screen==='archive')&&<><div className="section-toolbar"><div><h2>{screen==='templates'?'Шаблоны проектов':'Архив и корзина'}</h2><p>{screen==='templates'?'Маршруты и нормативы для повторяющегося производства':'Закрытые и удалённые проекты сохраняют свою историю'}</p></div></div><div className="project-cards">{w.projects.filter(p=>screen==='templates'?p.template:p.status!=='open').map(p=><div className="project-card" key={p.id}><Badge>{p.template?'Шаблон':p.status==='deleted'?'В корзине':'Закрыт'}</Badge><h3>{p.name}</h3><p>{p.code} · {p.stages.length} этапа</p><div className="actions"><button onClick={()=>open(p.id)}>Открыть</button>{p.template?<button className="primary" onClick={()=>run(()=>action(p.id,'clone'))}>Создать проект</button>:<button onClick={()=>run(()=>action(p.id,p.status==='deleted'?'restore':'reopen'))}><RotateCcw size={14}/>Восстановить</button>}</div></div>)}</div></>}
    {screen==='imports'&&<><div className="section-toolbar"><div><h2>Источники данных</h2><p>Снимок данных с предварительным просмотром. Проектные нормы сохраняются.</p></div><button onClick={()=>inputFile.current?.click()}><Upload size={16}/>Импорт проекта JSON</button></div><div className="source-card"><div className="source-icon"><Table2 size={26}/></div><div><h3>Google Sheets</h3><p>ЗАГРУЗ · Нормы · Лист14 · БД. СОТ · БД.ОП</p><Badge tone={connected?'green':'neutral'}>{demo?'Недоступно в автономном демо':connected?'Подключено · только чтение':'Не подключено'}</Badge></div><div className="actions">{!demo&&<><button onClick={()=>run(async()=>{const data=await client.current!.request('google/connect',{});window.location.assign(data.url);})}>{connected?'Переподключить':'Подключить Google'}</button><button className="primary" disabled={!connected||!!busy} onClick={()=>run(async()=>{setBusy('Читаем разрешённые листы…');try{setPreview(await client.current!.request('imports/preview',{timeUnit:secondsConfirmed?'seconds':undefined,employeesStartRow:employeesRow}));}finally{setBusy('');}})}><RotateCcw size={15}/>Обновить снимок</button></>}</div></div>{busy&&<p role="status">{busy}</p>}{preview&&<><div className="section-toolbar"><h3>Предварительный просмотр</h3><button className="primary" disabled={preview.diagnostics.some(d=>d.blocking)} onClick={()=>run(async()=>{setW(await client.current!.request(`imports/${preview.id}/apply`,{}));setPreview(undefined);notify('Снимок импортирован');})}>Применить импорт</button></div><div className="table-wrap"><table><thead><tr><th>Объект</th><th>Изменение</th></tr></thead><tbody>{preview.changes.map((c,i)=><tr key={i}><td>{c.name}</td><td>{({new:'Добавить',update:'Обновить справочник',unchanged:'Без изменений'})[c.action]}</td></tr>)}</tbody></table></div><h3>Диагностика</h3>{preview.diagnostics.map((d,i)=><div className={'import-diagnostic '+(d.blocking?'negative':'')} key={i}><Badge tone={d.blocking?'red':'amber'}>{d.blocking?'Ошибка':'Проверить'}</Badge><span>{d.sheet}, строка {d.row}: {d.message}</span></div>)}</>}
    <div className="source-note"><h3>Настройки импорта</h3><label className="check-row"><input type="checkbox" checked={secondsConfirmed} onChange={e=>setSecondsConfirmed(e.target.checked)}/>Подтверждаю: времена без единиц в БД.ОП указаны в секундах</label><Field label="ЗАГРУЗ: первая строка блока сотрудников"><input type="number" min="5" max="5000" value={employeesRow} onChange={e=>setEmployeesRow(+e.target.value)}/></Field><h3>Правила обновления</h3><p>Справочники читаются по заголовкам. Формулы с ошибками и неоднозначные нормы отмечаются в диагностике. Данные листов «Нормы» и «Лист14» сохраняются как референс; производственные задания из них автоматически не создаются.</p><p>Оборудование впервые импортируется с одним рабочим местом. Перед расчётом проверьте количество мест, календари и допуски сотрудников.</p></div></>}
    {screen==='project'&&!project&&<div className="empty-state"><Layers3 size={36}/><h2>Начните с проекта</h2><p>Создайте маршрут или загрузите демонстрационные данные.</p><div className="actions"><button className="primary" onClick={()=>setEdit(emptyProject(uid()))}>Создать проект</button>{!demo&&<button onClick={()=>run(async()=>{const data=await client.current!.request('demo/seed',{});setW(data);setSelected(data.projects[0].id);})}>Загрузить пример</button>}</div></div>}
  </div>}
  <footer className="app-footer"><span>Поток / Производственное планирование</span><span>{demo?'Пример данных · работает автономно':'Один планировщик · история изменений сохраняется'}</span></footer></main>
  <input ref={inputFile} type="file" accept="application/json,.json" hidden onChange={e=>{const f=e.target.files?.[0];if(f)run(async()=>{if(f.size>20_000_000)throw new Error('Файл больше 20 МБ');const next=await client.current!.importProject(JSON.parse(await f.text()));setW(next);notify('Проект импортирован');});e.target.value='';}}/>
  {edit&&<ProjectForm key={edit.id} project={edit} workspace={w} onSave={p=>run(()=>save(p))} onClose={()=>setEdit(undefined)}/>}
  {deleteProject&&<Modal title="Удалить проект?" onClose={()=>setDelete(undefined)}><p>Проект «{deleteProject.name}» переместится в корзину. Его можно будет восстановить.</p><Field label={'Введите номер: '+deleteProject.code}><input value={confirmCode} onChange={e=>setConfirmCode(e.target.value)}/></Field><footer className="modal-footer"><button onClick={()=>setDelete(undefined)}>Отмена</button><button className="danger solid" disabled={confirmCode!==deleteProject.code} onClick={()=>run(async()=>{await action(deleteProject.id,'delete',{confirm:confirmCode});setDelete(undefined);setScreen('archive');})}>Удалить</button></footer></Modal>}
  {planning&&project&&<Modal title="Автоматическое планирование" wide onClose={()=>{if(!busy)setPlanning(false);}}><p className="muted">Лучшие найденные варианты. Факт, закреплённые задания и другие проекты сохраняются.</p><div className="planning-modes"><button className={mode==='first'?'selected':''} onClick={()=>{setMode('first');setJob(undefined);}} disabled={!!busy}><Truck size={22}/><strong>Первая отгрузка</strong><span>Раньше получить готовую партию</span></button><button className={mode==='throughput'?'selected':''} onClick={()=>{setMode('throughput');setJob(undefined);}} disabled={!!busy}><Zap size={22}/><strong>Максимальная производительность</strong><span>Раньше завершить весь заказ</span></button></div><div className="planning-caption"><span>{num(project.quantity)} шт. · {project.employeeIds.length} сотрудников · буфер {project.bufferHours} ч</span><button className="primary" disabled={!!busy} onClick={calc}>{busy||'Рассчитать варианты'}</button></div>{busy&&<div className="calculating" role="status"><span className="spinner"/>{busy}</div>}{job?.scenarios&&<div className="scenarios">{job.scenarios.map((s,i)=><div className="scenario" key={s.id}><div className="scenario-title"><Badge tone={i===0?'green':'neutral'}>{i===0?'Самый ранний':'Вариант '+(i+1)}</Badge><strong>{num(s.firstQuantity)} <small>шт. в первой партии</small></strong></div><div className="scenario-data"><span>Первая готовность<b>{timeLabel(s.firstAt,project.zone)}</b></span><span>Весь заказ<b>{timeLabel(s.finishAt,project.zone)}</b></span><span>Свободное время<b>{num(s.idleHours,1)} чел·ч</b></span><span>Пик НЗП<b>{num(s.peakWip)} шт.</b></span></div>{s.warnings.map((v,i)=><p className="scenario-warning" key={i}>{v}</p>)}<details><summary>Причины и длительность свободных интервалов</summary><div className="table-wrap"><table><thead><tr><th>Сотрудник</th><th>Причина</th><th>Часы</th></tr></thead><tbody>{Object.entries((s.idlePeriods||[]).reduce((groups,gap)=>{const key=(w.employees.find(e=>e.id===gap.employeeId)?.name||gap.employeeId)+" | "+gap.reason;groups[key]=(groups[key]||0)+gap.hours;return groups;},{} as Record<string,number>)).map(([label,hours])=><tr key={label}><td>{label.split(" | ")[0]}</td><td>{label.split(" | ")[1]}</td><td>{num(hours,2)}</td></tr>)}</tbody></table></div></details><button className="primary" onClick={()=>run(async()=>{setW(await client.current!.apply(job.id,s));setPlanning(false);setTab('plan');notify('Вариант применён. Исходный план сохранён.');})}>Применить вариант <ArrowRight size={15}/></button></div>)}</div>}</Modal>}
  {detail&&current&&<Modal title="Производственное задание" onClose={()=>setDetail(undefined)}><div className="task-detail"><Badge>{current.stages.find(s=>s.id===detail.stageId)?.index}</Badge><h3>{current.stages.find(s=>s.id===detail.stageId)?.name}</h3><p>{current.stages.flatMap(s=>s.operations).find(o=>o.id===detail.operationId)?.name}</p><dl><dt>Начало</dt><dd>{timeLabel(detail.start,current.zone)}</dd><dt>Окончание</dt><dd>{timeLabel(detail.end,current.zone)}</dd><dt>Количество</dt><dd>{num(detail.quantity)} шт.</dd><dt>Исполнители</dt><dd>{detail.employeeIds.map(id=>w.employees.find(e=>e.id===id)?.name).join(', ')}</dd><dt>Закреплено</dt><dd>{detail.locked?'Да':'Нет'}</dd></dl></div><footer className="modal-footer"><button onClick={()=>{open(current.id);setTab('plan');setAssignment(detail);setDetail(undefined);}}>Изменить</button><button className="primary" onClick={()=>{open(current.id);setTab('plan');setActual(detail);setDetail(undefined);}}>Записать факт</button></footer></Modal>}
  {actual&&project&&<ActualForm project={project} assignment={actual} onClose={()=>setActual(undefined)} onSave={f=>run(async()=>{await action(project.id,'actuals',f);setActual(undefined);})}/>}
  {assignment!==undefined&&project&&<AssignmentForm project={project} workspace={w} initial={assignment||undefined} onClose={()=>setAssignment(undefined)} onError={setError} onSave={a=>run(async()=>{await action(project.id,'assignments',a);setAssignment(undefined);})}/>}
  {movement&&project&&<MovementForm project={project} onClose={()=>setMovement(false)} onSave={m=>run(async()=>{await action(project.id,'movements',m);setMovement(false);})}/>}
  </div></FormErrorContext.Provider>;
}
