import {useMemo,useState} from 'react';
import {Plus,ChevronDown,Package,ArrowUpRight} from 'lucide-react';
import {DateTime} from 'luxon';
import type {Project} from '../domain/types';
import {calculateNorm,actualMetrics} from '../domain/norms';
import {demand} from '../domain/graph';
import {assignmentMovements,dailyInventory} from '../domain/inventory';
import {num,dateLabel,Badge,timeLabel} from './components';
export function Norms({project}:{project:Project}){
  let required:Record<string,number>={};try{required=demand(project);}catch{}
  const rows=project.stages.flatMap(s=>s.operations.map(o=>{let n;try{n=calculateNorm(o.norm);}catch{}return {s,o,n};}));
  const labor=rows.reduce((sum,{s,o,n})=>sum+(n?(n.cycle*(required[s.id]||0)+n.setup)*(o.mode==='crew'?o.workers:1):0),0)/3600;
  return <><div className="section-toolbar"><div><h2>Нормативы производства</h2><p>Версия {project.normVersion} · нормы сохранены в проекте</p></div><Badge>{rows.length} операций</Badge></div><div className="report-summary"><div><span>Объём заказа</span><strong>{num(project.quantity)} <small>шт.</small></strong></div><div><span>Нормативные трудозатраты</span><strong>{num(labor,1)} <small>чел·ч</small></strong></div><div><span>Расчётное завершение</span><strong>{project.assignments.length?dateLabel(project.assignments.reduce((s,a)=>s>a.end?s:a.end,'')):'Нет плана'}</strong></div></div><div className="table-wrap"><table><thead><tr><th>Полуфабрикат / операция</th><th>Тип</th><th>Подготовка, с</th><th>Машина, с/шт.</th><th>Цикл, с/шт.</th><th>Выпуск, шт/ч</th><th>Потребность, шт.</th><th>Норма</th></tr></thead><tbody>{rows.map(({s,o,n},i)=><tr key={o.id}><td><div className="table-name"><span className={'number-box stage-'+project.stages.indexOf(s)%5}>{String(i+1).padStart(2,'0')}</span><div><strong>{o.name}</strong><small>{s.index} · {o.code}</small></div></div></td><td>{({linear:'Погонная',static:'Статичная',variable:'Переменная'})[o.norm.type]}</td><td>{num(n?.setup)}</td><td>{num(n?.machine,2)}</td><td><b>{num(n?.cycle,2)}</b></td><td>{num(n?.hourly,1)}</td><td>{num(required[s.id])}</td><td><Badge tone={o.norm.override?'amber':'green'}>{o.norm.override?'Ручная':'Расчётная'}</Badge></td></tr>)}</tbody></table></div></>;
}
export function ActualReport({project}:{project:Project}){return <div className="actual-report"><h3>Выполнение операций</h3><div className="table-wrap"><table><thead><tr><th>Операция</th><th>Обработано</th><th>Годных</th><th>Брак</th><th>Факт, с/шт.</th><th>Норма, с/шт.</th><th>Отклонение</th><th>Затраты на годную, чел·с</th></tr></thead><tbody>{project.stages.flatMap(s=>s.operations.map(op=>{const ids=new Set(project.assignments.filter(a=>a.operationId===op.id).map(a=>a.id));const m=actualMetrics(project.actuals.filter(f=>ids.has(f.assignmentId)));let n=0;try{n=calculateNorm(op.norm).cycle;}catch{}return <tr key={op.id}><td>{op.name}</td><td>{num(m.processed)}</td><td>{num(m.good)}</td><td>{num(m.scrap)}</td><td>{num(m.average,2)}</td><td>{num(n,2)}</td><td>{m.average===null?'—':<Badge tone={m.average>n?'amber':'green'}>{num((m.average/n-1)*100,1)}%</Badge>}</td><td>{num(m.perGood,2)}</td></tr>;}))}</tbody></table></div></div>;}
export function Materials({project,onNew}:{project:Project;onNew:()=>void}){
  const [selected,setSelected]=useState(project.stages.at(-1)?.id||''),[expanded,setExpanded]=useState<string>(),[period,setPeriod]=useState(0);
  const finish=project.assignments.reduce((s,a)=>s>a.end?s:a.end,project.deadline);const to=DateTime.fromISO(finish,{zone:project.zone}).toISODate()!;
  const planMoves=useMemo(()=>[...project.supplies.map(s=>({id:s.id,at:s.at,stageId:s.stageId,quantity:s.quantity,kind:'receipt' as const})),...assignmentMovements(project,project.assignments)],[project]);
  const planned=useMemo(()=>dailyInventory(project,planMoves,project.startDate,to),[project,planMoves,to]);
  const actual=useMemo(()=>dailyInventory(project,project.movements,project.startDate,to),[project,to]);
  const rows=planned.filter(r=>r.stageId===selected),visible=rows.slice(period*14,(period+1)*14);
  const values=rows.map(r=>r.cumulative),max=Math.max(1,...values),pts=values.map((v,i)=>`${40+i/Math.max(1,values.length-1)*860},${170-v/max*130}`).join(' ');
  return <><div className="section-toolbar"><div><h2>Движение материалов</h2><p>Выпуск, промежуточные запасы и отгрузки</p></div><button className="primary" onClick={onNew} disabled={!project.stages.length}><Plus size={16}/>Движение</button></div><div className="material-selector">{project.stages.map((s,i)=><button className={selected===s.id?'selected':''} key={s.id} onClick={()=>{setSelected(s.id);setPeriod(0);}}><i className={'legend-dot stage-'+i%5}/>{s.name}</button>)}</div><div className="material-chart"><div><span className="eyebrow">ВЫПУСК НАРАСТАЮЩИМ ИТОГОМ</span><h3>{num(values.at(-1)||0)} <small>шт. по плану</small></h3></div><svg viewBox="0 0 940 205" role="img" aria-label="Накопленный плановый выпуск"><line x1="40" x2="900" y1="170" y2="170" stroke="#dce3e7"/><line x1="40" x2="900" y1="40" y2="40" stroke="#eef1f3"/><text x="0" y="45">{num(max)}</text><text x="20" y="175">0</text><polyline points={pts} fill="none" stroke="#087f73" strokeWidth="2.5"/>{rows.length>0&&<><text x="40" y="195">{dateLabel(rows[0].date)}</text><text x="900" y="195" textAnchor="end">{dateLabel(rows.at(-1)!.date)}</text></>}</svg></div>
  <div className="table-wrap"><table><thead><tr><th rowSpan={2}>День</th><th colSpan={8}>План</th><th colSpan={8}>Факт</th></tr><tr><th>Начало</th><th>Приход</th><th>Расход</th><th>Выпуск</th><th>Брак</th><th>Отгружено</th><th>Остаток</th><th>Накоплено</th><th>Начало</th><th>Приход</th><th>Расход</th><th>Выпуск</th><th>Брак</th><th>Отгружено</th><th>Остаток</th><th>Накоплено</th></tr></thead><tbody>{visible.map(r=>{const a=actual.find(a=>a.date===r.date&&a.stageId===r.stageId)!;return <Rows key={r.date}><tr className="clickable" onClick={()=>setExpanded(expanded===r.date?undefined:r.date)}><td><ChevronDown size={12}/> {dateLabel(r.date)}</td>{[r.opening,r.receipt,r.consume,r.output,r.scrap,r.shipped,r.closing,r.cumulative,a.opening,a.receipt,a.consume,a.output,a.scrap,a.shipped,a.closing,a.cumulative].map((v,i)=><td key={i} className={v<0?'negative':''}>{num(v,2)}</td>)}</tr>{expanded===r.date&&<tr><td colSpan={17}><div className="event-list">{[...r.events.map(e=>({...e,source:'План'})),...a.events.map(e=>({...e,source:'Факт'}))].sort((a,b)=>a.at.localeCompare(b.at)).map(e=><span key={e.source+e.id}><b>{e.source}</b> {timeLabel(e.at,project.zone)} · {({opening:'Начальный остаток',receipt:'Приход',consume:'Расход',output:'Выпуск',scrap:'Брак',shipment:'Отгрузка',adjustment:'Корректировка'})[e.kind]} · {num(e.quantity,2)} шт. {e.note||''}</span>)}{!r.events.length&&!a.events.length&&<span>Нет движений за день</span>}</div></td></tr>}</Rows>;})}</tbody></table></div><div className="table-footer"><span>{rows.length} календарных дней</span><div className="actions"><button disabled={period===0} onClick={()=>setPeriod(period-1)}>Ранее</button><button disabled={(period+1)*14>=rows.length} onClick={()=>setPeriod(period+1)}>Далее</button></div></div></>;
}
function Rows({children}:{children:React.ReactNode}){return <>{children}</>;}
