import type {Project} from '../domain/types';
import {calculateNorm,actualMetrics} from '../domain/norms';
import {demand} from '../domain/graph';
import {stageNorm} from '../domain/reporting';
import {num,dateLabel,Badge,Hint} from './components';
export function Norms({project}:{project:Project}){
  let required:Record<string,number>={};try{required=demand(project);}catch{}
  const rows=project.stages.map(s=>({s,n:stageNorm(s,required[s.id])}));
  const labor=rows.length&&rows.every(r=>r.n?.laborHours!=null)?rows.reduce((sum,r)=>sum+r.n!.laborHours!,0):null;
  return <><div className="section-toolbar"><div className="actions"><h2>Нормативы производства</h2><Hint text="Одна строка — один полуфабрикат. Время единицы складывается из последовательных операций, с учётом ручных поправок. Календарное завершение берётся из расписания."/></div><Badge>Версия {project.normVersion} · {rows.length} полуфабрикатов</Badge></div><div className="report-summary"><div><span>Объём заказа</span><strong>{num(project.quantity)} <small>шт.</small></strong></div><div><span>Нормативные трудозатраты <Hint text="При коэффициенте 1, с учётом состава бригад и одной подготовки каждой операции. Повторные запуски и назначенные ресурсы уточняются в расписании."/></span><strong>{num(labor,1)} <small>чел·ч</small></strong></div><div><span>Расчётное завершение</span><strong>{project.assignments.length?dateLabel(project.assignments.reduce((s,a)=>s>a.end?s:a.end,'')):'Нет плана'}</strong></div></div><div className="table-wrap"><table><thead><tr><th>Полуфабрикат</th><th>Подготовка, с</th><th>Время единицы, с</th><th>Норматив, шт/ч <Hint text="3600 / сумма времени операций. Это справочный темп последовательного изготовления, а не выпуск всего участка с параллельными исполнителями."/></th><th>Потребность, шт.</th><th>Трудозатраты, чел·ч</th><th>Норма</th></tr></thead><tbody>{rows.map(({s,n},i)=><tr key={s.id}><td><div className="table-name"><span className={'number-box stage-'+i%5}>{String(i+1).padStart(2,'0')}</span><div><strong>{s.name}</strong><small>{s.index}</small></div></div></td><td>{num(n?.setup,2)}</td><td><b title={n?`Расчёт без поправок: ${num(n.calculated,2)} с`:undefined}>{num(n?.cycle,2)}</b></td><td>{num(n?.hourly,1)}</td><td>{num(required[s.id])}</td><td>{num(n?.laborHours,2)}</td><td><Badge tone={!n?'red':n.overridden?'amber':'green'}>{!n?'Нет нормы':n.overridden?'С поправкой':'Расчётная'}</Badge></td></tr>)}</tbody></table></div></>;
}
export function ActualReport({project}:{project:Project}){return <div className="actual-report"><h3>Выполнение операций</h3><div className="table-wrap"><table><thead><tr><th>Операция</th><th>Рабочее время</th><th>Обработано</th><th>Годных</th><th>Брак</th><th>Факт, с/шт.</th><th>Норма, с/шт.</th><th>Отклонение</th><th>Затраты на годную, чел·с</th></tr></thead><tbody>{project.stages.flatMap(s=>s.operations.map(op=>{const ids=new Set(project.assignments.filter(a=>a.operationId===op.id).map(a=>a.id));const m=actualMetrics(project.actuals.filter(f=>ids.has(f.assignmentId)));let n=0;try{n=calculateNorm(op.norm).cycle;}catch{}return <tr key={op.id}><td>{op.name}</td><td>{num(m.seconds/3600,2)} ч</td><td>{num(m.processed)}</td><td>{num(m.good)}</td><td>{num(m.scrap)}</td><td>{num(m.average,2)}</td><td>{num(n,2)}</td><td>{m.average===null?'—':<Badge tone={m.average>n?'amber':'green'}>{num((m.average/n-1)*100,1)}%</Badge>}</td><td>{num(m.perGood,2)}</td></tr>;}))}</tbody></table></div></div>;}
export {Materials} from './Materials';
