'use client';
import {useEffect,useState,useMemo} from 'react';
import {ReactFlow,Background,Controls,Handle,Position,applyNodeChanges,type NodeProps,type Node,type NodeChange} from '@xyflow/react';
import {Plus,Check,Trash2,RotateCcw,ArrowRight,GripVertical} from 'lucide-react';
import type {Project,Workspace,Stage,RouteOperation,Norm} from '../domain/types';
import {uid} from '../domain/types';
import {calculateNorm} from '../domain/norms';
import {topological} from '../domain/graph';
import {Field,num,Badge} from './components';
type StageNode=Node<{stage:Stage;selectedStage:boolean},'stage'>;
function Block({data}:NodeProps<StageNode>){const s=data.stage;let seconds=0;try{seconds=s.operations.reduce((sum,o)=>sum+calculateNorm(o.norm).cycle,0);}catch{}
  return <div className={'stage-node '+(data.selectedStage?'active':'')}><Handle type="target" position={Position.Left}/><div className="node-top"><span>{s.index}</span>{s.final?<Badge tone="green">Final</Badge>:<span className="node-dot"/>}</div><strong>{s.name}</strong><div className="node-rule"/><div className="node-meta"><span>{s.operations.length} {s.operations.length===1?'операция':'операции'}</span><b>{num(seconds,1)} с/шт.</b></div><Handle type="source" position={Position.Right}/></div>;
}
const nodeTypes={stage:Block};
export default function RouteEditor({project,workspace,onSave,onError}:{project:Project;workspace:Workspace;onSave:(p:Project)=>Promise<void>;onError:(s:string)=>void}){
  const [draft,setDraft]=useState(project),[selected,setSelected]=useState<string|undefined>(project.stages[0]?.id),[dirty,setDirty]=useState(false),[edgeId,setEdgeId]=useState<string>(),[search,setSearch]=useState('');
  useEffect(()=>{setDraft(project);setDirty(false);},[project]);
  const stage=draft.stages.find(s=>s.id===selected),edge=draft.edges.find(e=>e.id===edgeId);
  const edit=(p:Project)=>{setDraft(p);setDirty(true);};const editStage=(s:Stage)=>edit({...draft,stages:draft.stages.map(old=>old.id===s.id?s:old)});
  const editOp=(op:RouteOperation)=>stage&&editStage({...stage,operations:stage.operations.map(o=>o.id===op.id?op:o)});
  const nodes=useMemo(()=>draft.stages.map(s=>({id:s.id,type:'stage' as const,position:{x:s.x,y:s.y},data:{stage:s,selectedStage:s.id===selected}})),[draft.stages,selected]);
  const connect=(source:string,target:string)=>{const next={...draft,edges:[...draft.edges,{id:uid(),source,target,quantity:1,transferBatch:1}]};try{topological(next);edit(next);}catch(e){onError((e as Error).message);}};
  const onNodesChange=(changes:NodeChange<StageNode>[])=>{const updated=applyNodeChanges(changes,nodes);if(changes.some(c=>c.type==='position'&&c.position))edit({...draft,stages:draft.stages.map(s=>{const n=updated.find(n=>n.id===s.id);return n?{...s,x:n.position.x,y:n.position.y}:s;})});};
  const removeStage=()=>{if(!stage)return;if(!confirm(`Удалить блок «${stage.name}» и его связи?`))return;edit({...draft,stages:draft.stages.filter(s=>s.id!==stage.id),edges:draft.edges.filter(e=>e.source!==stage.id&&e.target!==stage.id)});setSelected(undefined);};
  return <div className="route-layout"><div className="route-main"><div className="section-toolbar"><div><h2>Маршрут производства</h2><p>От заготовки до готовой продукции</p></div><div className="actions"><button onClick={()=>{const s:Stage={id:uid(),index:'ПФ-'+String(draft.stages.length+1).padStart(3,'0'),name:'Новый полуфабрикат',final:false,x:80+draft.stages.length*80,y:330,operations:[]};edit({...draft,stages:[...draft.stages,s]});setSelected(s.id);}}><Plus size={16}/>Блок</button><button className="primary" disabled={!dirty} onClick={()=>onSave(draft)}><Check size={16}/>Сохранить</button></div></div>
    <div className="flow-canvas"><ReactFlow nodes={nodes} edges={draft.edges.map(e=>({id:e.id,source:e.source,target:e.target,label:`${e.quantity}:1 · партия ${e.transferBatch}`,type:'smoothstep',style:{stroke:'#9dabb6',strokeWidth:1.5},labelStyle:{fill:'#677889',fontSize:11},labelBgStyle:{fill:'#f7f9fa'}}))} nodeTypes={nodeTypes} onNodesChange={onNodesChange} onNodeClick={(_,n)=>{setSelected(n.id);setEdgeId(undefined);}} onEdgeClick={(_,e)=>{setEdgeId(e.id);setSelected(undefined);}} onConnect={c=>c.source&&c.target&&connect(c.source,c.target)} fitView minZoom={0.35} maxZoom={1.8} deleteKeyCode={null} proOptions={{hideAttribution:true}}><Background gap={22} color="#dce3e7"/><Controls showInteractive={false}/></ReactFlow></div><footer className="canvas-footer"><span><i className="legend-dot"/>Полуфабрикат</span><span><ArrowRight size={14}/>Передача партии</span><span className="right">{draft.stages.length} этапа · {draft.edges.length} перехода {dirty?' · есть изменения':''}</span></footer>
    <div className="route-summary"><div><span className="eyebrow">ПАРАМЕТРЫ ПОТОКА</span><h3>Каждый этап связан с запасом</h3><p>Материал поступает на следующий этап после завершения передаточной партии.</p></div><Field label="Целевой буфер, эффективных часов"><input type="number" min="0" step="0.25" value={draft.bufferHours} onChange={e=>edit({...draft,bufferHours:+e.target.value})}/></Field></div>
  </div><aside className="inspector">
    {edge&&<><div className="inspector-title"><h3>Переход между этапами</h3></div><Field label="Расход на единицу выпуска"><input type="number" min="0.001" step="0.1" value={edge.quantity} onChange={e=>edit({...draft,edges:draft.edges.map(x=>x.id===edge.id?{...x,quantity:+e.target.value}:x)})}/></Field><Field label="Передаточная партия, шт."><input type="number" min="1" value={edge.transferBatch} onChange={e=>edit({...draft,edges:draft.edges.map(x=>x.id===edge.id?{...x,transferBatch:+e.target.value}:x)})}/></Field><button className="danger" onClick={()=>{edit({...draft,edges:draft.edges.filter(x=>x.id!==edge.id)});setEdgeId(undefined);}}><Trash2 size={15}/>Удалить связь</button></>}
    {stage?<><div className="inspector-title"><span className="eyebrow">НАСТРОЙКА ЭТАПА</span><h3>{stage.index}</h3></div><Field label="Полуфабрикат"><input value={stage.name} onChange={e=>editStage({...stage,name:e.target.value})}/></Field><Field label="Производственный индекс"><input value={stage.index} onChange={e=>editStage({...stage,index:e.target.value})}/></Field><label className="check-row"><input type="checkbox" checked={stage.final} onChange={e=>edit({...draft,stages:draft.stages.map(s=>({...s,final:s.id===stage.id?e.target.checked:false}))})}/>Конечная продукция <Badge tone="green">Final</Badge></label>
    <div className="inspector-divider"/><h4>Операции <span className="muted">{stage.operations.length}</span></h4>
    {stage.operations.map((op,index)=>{let n;try{n=calculateNorm(op.norm);}catch{}return <details className="operation-editor" open key={op.id}><summary><GripVertical size={14}/><span>{index+1}. {op.name}</span></summary><div className="operation-body"><small className="mono">{op.code}</small><div className="form-grid"><Field label="Исполнителей"><input type="number" min="1" value={op.workers} onChange={e=>editOp({...op,workers:+e.target.value})}/></Field><Field label="Работа"><select value={op.mode} onChange={e=>editOp({...op,mode:e.target.value as RouteOperation['mode']})}><option value="independent">Независимо</option><option value="crew">Бригада</option></select></Field></div>
    <Field label="Оборудование"><select value={op.norm.machineId||''} onChange={e=>editOp({...op,norm:{...op.norm,machineId:e.target.value||undefined}})}><option value="">Ручная операция</option>{workspace.machines.map(m=><option key={m.id} value={m.id}>{m.name}</option>)}</select></Field>
    <Field label="Тип нормы"><select value={op.norm.type} onChange={e=>editOp({...op,norm:{...op.norm,type:e.target.value as Norm['type']}})}><option value="linear">Погонный</option><option value="static">Статичный</option><option value="variable">Переменный</option></select></Field>
    <div className="form-grid">{([...(op.norm.type==='linear'?[['length','Длина, м'],['secondsPerMeter','Прокат, с/м']]:[]),['take','Взять, с'],['work','Работа, с'],['put','Снять, с'],['extra','Дополнительно, с'],['toolSeconds','Инструмент, с'],['toolCount','Действий инструмента'],['repeats','Повторений'],['setup','Подготовка, с']] as [keyof Norm,string][]).map(([key,label])=><Field key={key} label={label}><input type="number" min="0" step="0.1" value={Number(op.norm[key]||0)} onChange={e=>editOp({...op,norm:{...op.norm,[key]:+e.target.value}})}/></Field>)}</div>
    <div className="calculated"><span>Расчётная норма</span><strong>{num(n?.calculated,2)} <small>с/шт.</small></strong></div><Field label="Ручная поправка, с/шт." hint={n?`Минимум по машине: ${num(n.machine,2)} с`:undefined}><input type="number" min={n?.machine||0.01} step="0.1" placeholder="Использовать расчёт" value={op.norm.override??''} onChange={e=>editOp({...op,norm:{...op.norm,override:e.target.value===''?undefined:+e.target.value}})}/></Field><div className="actions"><button className="text-button" onClick={()=>editOp({...op,norm:{...op.norm,override:undefined}})}><RotateCcw size={13}/>Вернуть расчёт</button><button className="icon-button danger" aria-label="Удалить операцию" onClick={()=>editStage({...stage,operations:stage.operations.filter(o=>o.id!==op.id)})}><Trash2 size={14}/></button></div>{index>0&&<button className="text-button" onClick={()=>{const list=[...stage.operations];[list[index-1],list[index]]=[list[index],list[index-1]];editStage({...stage,operations:list});}}>Переместить выше</button>}</div></details>;})}
    <Field label="Добавить из справочника"><input placeholder="Поиск операции…" value={search} onChange={e=>setSearch(e.target.value)}/><select value="" onChange={e=>{const o=workspace.operations.find(o=>o.id===e.target.value);if(o)editStage({...stage,operations:[...stage.operations,{id:uid(),operationId:o.id,code:o.code,name:o.name,norm:structuredClone(o.norm),workers:1,mode:'independent'}]});}}><option value="">Выберите операцию</option>{workspace.operations.filter(o=>(o.name+' '+o.code).toLowerCase().includes(search.toLowerCase())).map(o=><option key={o.id} value={o.id}>{o.code} · {o.name}</option>)}</select></Field><button className="text-button danger" onClick={removeStage}><Trash2 size={14}/>Удалить блок</button>
    </>:!edge&&<p className="empty-small">Выберите блок или связь на схеме.</p>}
  </aside></div>;
}
