import {useState} from 'react';
import {DateTime} from 'luxon';
import {ArrowLeftRight,Plus,LockKeyhole,ChevronLeft,ChevronRight,CalendarDays} from 'lucide-react';
import type {Workspace,Project,Assignment} from '../domain/types';
import {num,dateLabel,timeLabel,Badge} from './components';
export function Timeline({workspace,project,onAssignment,onNew,onProject}:{workspace:Workspace;project?:Project;onAssignment:(a:Assignment)=>void;onNew?:()=>void;onProject?:(id:string)=>void}){
  const [scale,setScale]=useState<'day'|'week'|'month'>('week'),[transpose,setTranspose]=useState(false),[offset,setOffset]=useState(0),[expandedCell,setExpandedCell]=useState<string>();
  const projects=project?[project]:workspace.projects.filter(p=>p.status==='open'&&!p.template),zone=project?.zone||projects[0]?.zone||'Asia/Shanghai';
  const origin=DateTime.fromISO(project?.startDate||projects[0]?.startDate||new Date().toISOString().slice(0,10),{zone}).plus({days:offset});
  const length=scale==='day'?12:scale==='week'?7:30;
  const columns=Array.from({length},(_,i)=>scale==='day'?origin.set({hour:7}).plus({hours:i}):origin.plus({days:i}));
  const assignments=projects.flatMap(p=>p.assignments),employees=workspace.employees.filter(e=>!project||project.employeeIds.includes(e.id));
  const cellAssignments=(person:string,index:number)=>{const a=columns[index],b=a.plus(scale==='day'?{hours:1}:{days:1});return assignments.filter(x=>x.employeeIds.includes(person)&&x.segments.some(s=>DateTime.fromISO(s.start)<b&&DateTime.fromISO(s.end)>a)).sort((a,b)=>a.start.localeCompare(b.start));};
  const stageColor=(a:Assignment)=>{const p=projects.find(p=>p.id===a.projectId)!;return 'stage-'+(Math.max(0,p.stages.findIndex(s=>s.id===a.stageId))%5);};
  const actual=(person:string,index:number)=>{const a=columns[index],b=a.plus(scale==='day'?{hours:1}:{days:1});return projects.flatMap(p=>p.actuals.map(f=>({...f,project:p}))).filter(f=>f.employeeIds.includes(person)&&DateTime.fromISO(f.end)>=a&&DateTime.fromISO(f.end)<b);};
  const cell=(person:string,index:number)=><div className="timeline-cell"><div className="plan-lane">{cellAssignments(person,index).slice(0,expandedCell===person+index?undefined:4).map(a=>{const p=projects.find(p=>p.id===a.projectId)!,s=p.stages.find(s=>s.id===a.stageId);return <button className={'task-block '+stageColor(a)} key={a.id} onClick={()=>onAssignment(a)} title={`${s?.name} · ${timeLabel(a.start,zone)} — ${timeLabel(a.end,zone)}`}><span>{s?.index} {a.locked&&<LockKeyhole size={10}/>}</span><b>{num(a.quantity)} шт.</b></button>;})}{cellAssignments(person,index).length>4&&<button className="more-tasks" onClick={()=>setExpandedCell(expandedCell===person+index?undefined:person+index)}>{expandedCell===person+index?'Свернуть':'Ещё '+(cellAssignments(person,index).length-4)}</button>}</div><div className="actual-lane">{actual(person,index).length?<span>{num(actual(person,index).reduce((s,f)=>s+f.processed-f.scrap,0))} годных</span>:<span className="dash">—</span>}</div></div>;
  return <><div className="section-toolbar"><div><h2>{project?'Загрузка команды':'Общий ресурсный план'}</h2><p>План и факт на одной временной шкале</p></div><div className="actions"><button onClick={()=>setTranspose(!transpose)}><ArrowLeftRight size={15}/>{transpose?'По сотрудникам':'Повернуть оси'}</button>{onNew&&<button className="primary" onClick={onNew}><Plus size={16}/>Задание</button>}</div></div><div className="timeline-toolbar"><div className="actions"><button className="icon-button" aria-label="Предыдущий период" onClick={()=>setOffset(offset-(scale==='month'?30:scale==='week'?7:1))}><ChevronLeft size={17}/></button><CalendarDays size={16}/><strong>{dateLabel(origin.toISODate()!)} — {dateLabel(columns.at(-1)!.toISODate()!)}</strong><button className="icon-button" aria-label="Следующий период" onClick={()=>setOffset(offset+(scale==='month'?30:scale==='week'?7:1))}><ChevronRight size={17}/></button></div><div className="segmented">{(['day','week','month'] as const).map((v,i)=><button key={v} className={scale===v?'selected':''} onClick={()=>setScale(v)}>{['День','Неделя','Месяц'][i]}</button>)}</div></div>
  <div className="timeline-scroll"><table className={'timeline-table '+(scale==='month'?'compact':'')}><thead><tr><th>{transpose?'Время':'Сотрудник / проект'}</th>{transpose?employees.map(e=><th key={e.id}>{e.name}</th>):columns.map((d,i)=><th className={d.weekday>5?'weekend':''} key={i}><span>{scale==='day'?d.toFormat('HH:mm'):d.setLocale('ru').toFormat('ccc')}</span><b>{scale==='day'?d.toFormat('dd.MM'):d.setLocale('ru').toFormat('d MMM')}</b></th>)}</tr></thead><tbody>
  {!transpose&&!project&&projects.map(p=><tr className="project-lane" key={p.id}><th><button onClick={()=>onProject?.(p.id)}>{p.name}</button><small>{p.code} · {Object.values(p.readiness).every(Boolean)?"Готов к запуску":"Проверить готовность"}</small></th>{columns.map((d,i)=><td key={i}>{p.deadline===d.toISODate()?<Badge tone="red">Дедлайн</Badge>:p.supplies.some(s=>DateTime.fromISO(s.at,{zone:p.zone}).toISODate()===d.toISODate())?<Badge tone="amber">Поставка</Badge>:p.assignments.some(a=>DateTime.fromISO(a.start,{zone:p.zone}).toISODate()!<=d.toISODate()!&&DateTime.fromISO(a.end,{zone:p.zone}).toISODate()!>=d.toISODate()!)?<span className="project-span"/>:null}</td>)}</tr>)}
  {transpose?columns.map((d,i)=><tr key={i}><th>{scale==='day'?d.toFormat('HH:mm'):d.setLocale('ru').toFormat('dd MMM, ccc')}</th>{employees.map(e=><td key={e.id}>{cell(e.id,i)}</td>)}</tr>):employees.map((e,i)=><tr key={e.id}><th><div className="person-cell"><div className={'avatar avatar-'+i%4}>{e.name.split(' ').map(x=>x[0]).join('').slice(0,2)}</div><div><strong>{e.name}</strong><small>{e.calendar.effectiveHours} ч/день · <span className="status-dot"/>Доступен</small></div></div><div className="lane-labels"><span>ПЛАН</span><span>ФАКТ</span></div></th>{columns.map((d,index)=><td key={index} className={d.weekday>5?'weekend':''}>{cell(e.id,index)}</td>)}</tr>)}
  </tbody></table></div><div className="timeline-legend">{(project?.stages||projects[0]?.stages||[]).map((s,i)=><span key={s.id}><i className={'legend-dot stage-'+i%5}/>{s.name}</span>)}<span className="right">{assignments.length} заданий</span></div>{assignments.length===0&&<div className="empty-state"><CalendarDays size={28}/><h3>План ещё не заполнен</h3><p>Создайте задание или запустите автопланирование.</p></div>}</>;
}
