import {useMemo,useState} from 'react';
import {DateTime} from 'luxon';
import {ArrowLeftRight,Plus,LockKeyhole,ChevronLeft,ChevronRight,CalendarDays} from 'lucide-react';
import type {Workspace,Project,Assignment} from '../domain/types';
import {assignmentInPeriod,completesIn,groupWork,type WorkGroup} from '../domain/reporting';
import {num,dateLabel,timeLabel,Badge,Hint,Modal} from './components';

export function Timeline({workspace,project,onAssignment,onNew,onProject}:{workspace:Workspace;project?:Project;onAssignment:(a:Assignment)=>void;onNew?:()=>void;onProject?:(id:string)=>void}){
  const [scale,setScale]=useState<'day'|'week'|'month'>('week'),[transpose,setTranspose]=useState(false),[offset,setOffset]=useState(0);
  const [view,setView]=useState<'group'|'piece'>('group'),[expandedCell,setExpandedCell]=useState<string>();
  const [selected,setSelected]=useState<{group:WorkGroup;person:string;date:string;from:number;to:number}>(),[page,setPage]=useState(0);
  const projects=useMemo(()=>project?[project]:workspace.projects.filter(p=>p.status==='open'&&!p.template),[workspace.projects,project]);
  const zone=project?.zone||projects[0]?.zone||'Asia/Shanghai';
  const origin=DateTime.fromISO(project?.startDate||projects[0]?.startDate||new Date().toISOString().slice(0,10),{zone}).startOf('day').plus({days:offset});
  // A full day includes configurable evening and night shifts too.
  const columns=Array.from({length:scale==='day'?24:scale==='week'?7:30},(_,i)=>origin.plus(scale==='day'?{hours:i}:{days:i}));
  const assignments=projects.flatMap(p=>p.assignments);
  const employees=workspace.employees.filter(e=>!project||project.employeeIds.includes(e.id)||project.assignments.some(a=>a.employeeIds.includes(e.id))||project.actuals.some(f=>f.employeeIds.includes(e.id)));
  const cells=useMemo(()=>new Map(employees.flatMap(e=>columns.map((d,index)=>{
    const from=d.toMillis(),to=d.plus(scale==='day'?{hours:1}:{days:1}).toMillis();
    return [`${e.id}/${index}`,{from,to,groups:groupWork(projects,e.id,from,to),tasks:assignments.filter(a=>a.employeeIds.includes(e.id)&&assignmentInPeriod(a,from,to)).sort((a,b)=>Date.parse(a.start)-Date.parse(b.start))}] as const;
  }))),[workspace,project,scale,offset]);
  const stageColor=(p:Project,stageId:string)=>'stage-'+Math.max(0,p.stages.findIndex(s=>s.id===stageId))%5;
  const openGroup=(group:WorkGroup,person:string,index:number)=>{const {from,to}=cells.get(`${person}/${index}`)!;setSelected({group,person,date:columns[index].toISO()!,from,to});setPage(0);};
  const cell=(person:string,index:number)=>{
    const {from,to,groups,tasks}=cells.get(`${person}/${index}`)!;
    const key=`${person}/${index}`,expanded=expandedCell===key;
    return <div className={'timeline-cell '+(view==='group'?'grouped-cell':'')}>
      {view==='group'?<><div className="group-lane-labels"><span>ПЛАН</span><span>ФАКТ</span></div>{groups.map(g=><button className={'work-group '+stageColor(g.project,g.stage.id)} key={g.key} onClick={()=>openGroup(g,person,index)} title={`${g.stage.name}. ${g.assignments.length} заданий. ${g.crew?'Выпуск бригады общий для всех участников. ':''}Открыть задания и факт.`}>
        <span className="group-name">{g.stage.name} {g.assignments.some(a=>a.locked)&&<LockKeyhole size={10}/>}</span>
        {!project&&<small>{g.project.code}</small>}
        <span className="group-quantities"><b>{g.plannedOutput?num(g.plannedOutput)+' шт.':g.assignments.length?'В работе':'—'}</b><b>{g.actuals.length?num(g.actualOutput)+' шт.':'—'}</b></span>
      </button>)}{!groups.length&&<span className="dash">—</span>}</>:<>
        <div className="plan-lane">{tasks.slice(0,expanded?undefined:4).map(a=>{const p=projects.find(p=>p.id===a.projectId)!,s=p.stages.find(s=>s.id===a.stageId);const finished=completesIn(a.end,from,to);return <button className={'task-block '+stageColor(p,a.stageId)} key={a.id} onClick={()=>onAssignment(a)} title={`${s?.name} · ${s?.operations.find(o=>o.id===a.operationId)?.code} · партия ${a.quantity} шт. · ${timeLabel(a.start,zone)} — ${timeLabel(a.end,zone)}`}><span>{s?.index} {a.locked&&<LockKeyhole size={10}/>}</span><b>{finished?num(a.quantity)+(a.operationId===s?.operations.at(-1)?.id?' шт.':' обраб.'):'В работе'}</b></button>;})}{tasks.length>4&&<button className="more-tasks" onClick={()=>setExpandedCell(expanded?undefined:key)}>{expanded?'Свернуть':'Ещё '+(tasks.length-4)}</button>}</div>
        <div className="actual-lane">{groups.filter(g=>g.actuals.length).map(g=><button className="actual-cell-button" key={g.key} onClick={()=>openGroup(g,person,index)} title={`${g.stage.name}: годный выпуск; брак ${g.scrap}`}><span>{g.stage.index}</span><b>{num(g.actualOutput)} годных</b></button>)}{!groups.some(g=>g.actuals.length)&&<span className="dash">—</span>}</div>
      </>}
    </div>;
  };
  const selectedAssignments=selected?selected.group.project.assignments.filter(a=>selected.group.assignments.some(t=>t.id===a.id)||selected.group.actuals.some(f=>f.assignmentId===a.id)).sort((a,b)=>Date.parse(a.start)-Date.parse(b.start)):[];
  return <><div className="section-toolbar"><div className="actions"><h2>{project?'Загрузка команды':'Общий ресурсный план'}</h2><Hint text="Групповой вид объединяет задания сотрудника по полуфабрикату за день (в масштабе «День» — за час). Выпуск учитывается один раз, при завершении последней операции блока. У бригады показан общий выпуск, его нельзя складывать по участникам. Нажмите строку для работы с заданиями."/></div><div className="actions"><button onClick={()=>setTranspose(!transpose)}><ArrowLeftRight size={15}/>{transpose?'По сотрудникам':'Повернуть оси'}</button>{onNew&&<button className="primary" onClick={onNew}><Plus size={16}/>Задание</button>}</div></div>
    <div className="timeline-view-toolbar"><div className="segmented" aria-label="Представление заданий"><button aria-pressed={view==='piece'} className={view==='piece'?'selected':''} onClick={()=>setView('piece')}>Поштучное представление</button><button aria-pressed={view==='group'} className={view==='group'?'selected':''} onClick={()=>setView('group')}>Групповое представление</button></div></div>
    <div className="timeline-toolbar"><div className="actions"><button className="icon-button" aria-label="Предыдущий период" onClick={()=>setOffset(offset-(scale==='month'?30:scale==='week'?7:1))}><ChevronLeft size={17}/></button><CalendarDays size={16}/><strong>{dateLabel(origin.toISODate()!)} — {dateLabel(columns.at(-1)!.toISODate()!)}</strong><button className="icon-button" aria-label="Следующий период" onClick={()=>setOffset(offset+(scale==='month'?30:scale==='week'?7:1))}><ChevronRight size={17}/></button></div><div className="segmented">{(['day','week','month'] as const).map((v,i)=><button key={v} className={scale===v?'selected':''} onClick={()=>setScale(v)}>{['День','Неделя','Месяц'][i]}</button>)}</div></div>
    <div className="timeline-scroll"><table className={'timeline-table '+(scale==='month'?'compact':'')}><thead><tr><th>{transpose?'Время':'Сотрудник / проект'}</th>{transpose?employees.map(e=><th key={e.id}>{e.name}</th>):columns.map((d,i)=><th className={d.weekday>5?'weekend':''} key={i}><span>{scale==='day'?d.toFormat('HH:mm'):d.setLocale('ru').toFormat('ccc')}</span><b>{scale==='day'?d.toFormat('dd.MM'):d.setLocale('ru').toFormat('d MMM')}</b></th>)}</tr></thead><tbody>
      {!transpose&&!project&&projects.map(p=><tr className="project-lane" key={p.id}><th><button onClick={()=>onProject?.(p.id)}>{p.name}</button><small>{p.code} · {Object.values(p.readiness).every(Boolean)?'Готов к запуску':'Проверить готовность'}</small></th>{columns.map((d,i)=><td key={i}>{p.deadline===d.toISODate()?<Badge tone="red">Дедлайн</Badge>:p.supplies.some(s=>DateTime.fromISO(s.at,{zone:p.zone}).toISODate()===d.toISODate())?<Badge tone="amber">Поставка</Badge>:p.assignments.some(a=>DateTime.fromISO(a.start,{zone:p.zone}).toISODate()!<=d.toISODate()!&&DateTime.fromISO(a.end,{zone:p.zone}).toISODate()!>=d.toISODate()!)?<span className="project-span"/>:null}</td>)}</tr>)}
      {transpose?columns.map((d,i)=><tr key={i}><th>{scale==='day'?d.toFormat('HH:mm'):d.setLocale('ru').toFormat('dd MMM, ccc')}</th>{employees.map(e=><td key={e.id}>{cell(e.id,i)}</td>)}</tr>):employees.map((e,i)=><tr key={e.id}><th><div className="person-cell"><div className={'avatar avatar-'+i%4}>{e.name.split(' ').map(x=>x[0]).join('').slice(0,2)}</div><div><strong>{e.name}</strong><small>{e.calendar.effectiveHours} ч/день</small></div></div>{view==='piece'&&<div className="lane-labels"><span>ПЛАН</span><span>ФАКТ</span></div>}</th>{columns.map((d,index)=><td key={index} className={d.weekday>5?'weekend':''}>{cell(e.id,index)}</td>)}</tr>)}
    </tbody></table></div><div className="timeline-legend">{(project?.stages||projects[0]?.stages||[]).map((s,i)=><span key={s.id}><i className={'legend-dot stage-'+i%5}/>{s.name}</span>)}<span className="right">{assignments.length} заданий</span></div>
    {assignments.length===0&&<div className="empty-state"><CalendarDays size={28}/><h3>План ещё не заполнен</h3></div>}
    {selected&&<Modal title={selected.group.stage.name} onClose={()=>setSelected(undefined)} wide><div className="actions group-detail-meta"><Badge>{workspace.employees.find(e=>e.id===selected.person)?.name}</Badge><Badge>{timeLabel(selected.date,zone)}</Badge><Badge>План: {num(selected.group.plannedOutput)} шт.</Badge><Badge tone="green">Факт: {num(selected.group.actualOutput)} шт.</Badge>{selected.group.crew&&<Badge>Общий выпуск бригады</Badge>}</div><div className="table-wrap"><table><thead><tr><th>Операция</th><th>Начало</th><th>Конец</th><th>Партия, шт.</th><th>Факт, обработано</th><th>Брак</th><th/></tr></thead><tbody>{selectedAssignments.slice(page*30,(page+1)*30).map(a=>{const facts=selected.group.actuals.filter(f=>f.assignmentId===a.id&&completesIn(f.end,selected.from,selected.to));return <tr key={a.id}><td>{selected.group.stage.operations.find(o=>o.id===a.operationId)?.code} {a.locked&&<LockKeyhole size={11}/>}</td><td>{timeLabel(a.start,zone)}</td><td>{timeLabel(a.end,zone)}</td><td>{num(a.quantity)}</td><td>{num(facts.reduce((sum,f)=>sum+f.processed,0))}</td><td>{num(facts.reduce((sum,f)=>sum+f.scrap,0))}</td><td><button onClick={()=>{setSelected(undefined);onAssignment(a);}}>Открыть</button></td></tr>;})}</tbody></table></div><div className="table-footer"><span>{selectedAssignments.length} заданий</span><div className="actions"><button disabled={page===0} onClick={()=>setPage(page-1)}>Ранее</button><button disabled={(page+1)*30>=selectedAssignments.length} onClick={()=>setPage(page+1)}>Далее</button></div></div></Modal>}
  </>;
}
